### ISSUE TITLE
Dérivée Application Trapta

### ISSUE THREAD

**Issue by Feunor** [TRAPTAProject/trapta-app#3]
Bonjour,

Je suis Président d'une association le Viking Normandie Barbe Moustache Club. Depuis quelqu'un je réfléchis à une application comme trapta mais pour les championnats de barbe et moustache, avec 7 membres du jury qui mettent leurs notes sur une tablette et à afficher en direct sur écran. Je recherche un développeur pour m'aider à réaliser ce dérivée de l'application Trapta.

Cordialement,

Guillaume

**Comment by GuillaumeEscande** [comment]
Bonjour,

On peut en discuter par téléphone ou par mail, plustot que par issue sur le projet trapta-app.
Mes coordonnées sont disponible ici :
https://escande.ovh/

Bien Cordialement
Guillaume Escande
Mainteneur TRAPTA
